### ISSUE TITLE
overflowed-literals

### ISSUE THREAD

**Issue by chessai** [andrewthad/primitive-median#2]
Some of the `Int` literals in this repo are overflowed. Is this intentional?

**Comment by andrewthad** [comment]
It is. Even if they weren't, if you built this on a 32-bit platform, you'd get the warning. If you want to suppress the warning, you probably do this instead:

    writePrimArray m 12 (wordToInt (0x5AA8FF325AD1CF66 :: Word))
    where
    wordToInt = fromIntegral :: Word -> Int

**Comment by chessai** [comment]
I could just do `-fno-warn-overflowed-literals`, but I feel like that might be unsafe.

**Comment by andrewthad** [comment]
Yeah, I would prefer the explicit cast over that. To return to the original question, it's nice to allow them to overflow since that lets us (1) capture the full range of `Int` (2) easily generate more entropy if we decide that 16 values is not enough. It's annoying to have to remember a set of transformations you have to perform on the data that comes from `/dev/random`.
